### ISSUE TITLE
can't invite my friend via Email

### ISSUE THREAD

**Issue by thanhlamqwe** [docsion/uppls#7]
hey Sir!. I have an issue, the function search people via email work fine, but when I hit invite button, nothing happend, my Friend (KieuHuy) said he used that feature so good this morning. but when I use it not working. I Tried to remote and reinstall but nothing change. hope it work next patch. 
Docsion 0.5.2

**Comment by beastoin** [comment]
Hey @thanhlamqwe , we have a good new for you. Actually, the doc is shared, but, the notification system does not work because of dropping the real-time connection. So:

1/ Will fix, you can work around by closing the application and reopen.
2/ You can try the Docsion v0.5.3 https://github.com/docsion/uppls, with a ton of bugs were killed and love.

Keep going 🚀 
Thịnh

**Comment by beastoin** [comment]
Hey mate, problem resolved @ Docsion v0.6.1 @ enjoy ❤️
